### ISSUE TITLE
File should install under expathrepo with version number

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/eXistentializer#9]
When we build an app that we bootstrapped with the initializer, it seems to install under _expathrepo_ with just the app name, although what we want it to do instead is include the version number. For example, we wind up with _expathrepo/init_ and we should have _expathrepo/init-0.0.1_.

**Comment by gabikeane** [comment]
Tests were not able to reproduce. Closing this issue.
